{% set version = "0.10.0" %}
{% set cxx_version = "0.10.0" %}

package:
  name: symengine-wheels
  version: {{ version }}

source:
  - url: https://github.com/symengine/symengine.py/archive/f7e0f28a7badbcd70426ed938767acbbce41d7f1.tar.gz
    folder: python

  - url: https://github.com/symengine/symengine/archive/324b2e0a012a2b86fd94110824d5618477f848c6.tar.gz
    folder: cxx

build:
  number: 0
  ignore_run_exports_from:
    - gmp
    - mpfr
    - mpc
    - libflint
    - llvmdev
    - zlib
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [unix]
    - ninja  # [win]
    - unzip           # [unix]
    - patchelf        # [linux]
    - python          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - setuptools      # [build_platform != target_platform]
    - auditwheel      # [linux]
    - delocate        # [win]
    - pip             # [osx]
    - packaging       # [osx]
    - cython >=0.29.24
  host:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - libflint 2.* *nontl*
    - llvmdev
    - zlib
    - python
    - setuptools
    - cython >=0.29.24  # [build_platform == target_platform]
    - pip
  run:
    - python

test:
  requires:
    - pytest
    - sympy
    - numpy

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: python/LICENSE
  summary: Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
