{% set version = "0.13.0" %}
{% set cxx_version = "0.13.0" %}

package:
  name: symengine-wheels
  version: {{ version }}

source:
  - url: https://github.com/symengine/symengine.py/releases/download/v{{ version }}/symengine.py-{{ version }}.tar.gz
    sha256: fa48beb9b8d4574482edf19dc8671d4cb78f53c2511047a0e52bb88fbdeb6d0c
    folder: python

  - url: https://github.com/symengine/symengine/releases/download/v{{ cxx_version }}/symengine-{{ cxx_version }}.tar.gz
    sha256: f46bcf037529cd1a422369327bf360ad4c7d2b02d0f607a62a5b09c74a55bb59
    folder: cxx

build:
  number: 0
  ignore_run_exports_from:
    - gmp
    - mpfr
    - mpc
    - libflint
    - llvmdev
    - zlib
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make   # [unix]
    - ninja  # [win]
    - patchelf        # [linux]
    - python          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - setuptools      # [build_platform != target_platform]
    - unzip           # [unix]
    - m2-unzip        # [win]
    - cython >=0.29.24
  host:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - libflint 3.0.*
    - llvmdev <17
    - zlib
    - python
    - setuptools
    - cython >=0.29.24  # [build_platform == target_platform]
    - pip
    - auditwheel      # [linux]
    - delocate        # [win or osx]
  run:
    - python

test:
  requires:
    - pytest
    - sympy
    - numpy

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: python/LICENSE
  summary: Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
