{% set version = "0.14.0" %}
{% set cxx_version = "0.14.0" %}

package:
  name: symengine-wheels
  version: {{ version }}

source:
  - url: https://github.com/symengine/symengine.py/releases/download/v{{ version }}/symengine.py-{{ version }}.tar.gz
    sha256: 38e742a9b3d03b36f07b2ccba39e7e3d626e37557c26bb03ce575b95cfbd9cc4
    folder: python

  - url: https://github.com/symengine/symengine/releases/download/v{{ cxx_version }}/symengine-{{ cxx_version }}.tar.gz
    sha256: 11c5f64e9eec998152437f288b8429ec001168277d55f3f5f1df78e3cf129707
    folder: cxx

build:
  number: 0
  ignore_run_exports_from:
    - gmp
    - mpfr
    - mpc
    - libflint
    - llvmdev
    - zlib
    - zstd
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make   # [unix]
    - ninja  # [win]
    - patchelf        # [linux]
    - python          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - setuptools      # [build_platform != target_platform]
    - unzip           # [unix]
    - m2-unzip        # [win]
    - m2-sed          # [win]
    - cython >=0.29.24
  host:
    - gmp
    - mpfr
    - mpc
    - libflint
    - winpthreads-devel  # [win]
    - llvmdev <17
    # for llvm
    - zlib
    # for llvm
    - zstd
    - python
    - setuptools
    - cython >=0.29.24  # [build_platform == target_platform]
    - pip
    - auditwheel      # [linux]
    - delocate        # [win or osx]
  run:
    - python

test:
  requires:
    - pytest
    - sympy
    - numpy   # [not is_freethreading]

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: python/LICENSE
  summary: Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
