{% set version = "0.10.0" %}
{% set cxx_version = "0.10.1" %}

package:
  name: symengine-wheels
  version: {{ version }}

source:
  - url: https://github.com/symengine/symengine.py/releases/download/v{{ version }}/symengine.py-{{ version }}.tar.gz
    sha256: 923944ab54aa0a787629424c101f5ec6a87b44177c669d21c7d3b0257f725927
    folder: python

  - url: https://github.com/symengine/symengine/releases/download/v{{ cxx_version }}/symengine-{{ cxx_version }}.tar.gz
    sha256: 9c007c99e9633f5549a55fa7a66ebcbcf9e04092eb55f7bb781c22b9cf0570c4
    folder: cxx

build:
  number: 0
  ignore_run_exports_from:
    - gmp
    - mpfr
    - mpc
    - libflint
    - llvmdev
    - zlib
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [unix]
    - ninja  # [win]
    - unzip           # [unix]
    - patchelf        # [linux]
    - python          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - setuptools      # [build_platform != target_platform]
    - auditwheel      # [linux]
    - delocate        # [win]
    - pip             # [osx]
    - packaging       # [osx]
    - cython >=0.29.24
  host:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - libflint 2.* *nontl*
    - llvmdev
    - zlib
    - python
    - setuptools
    - cython >=0.29.24  # [build_platform == target_platform]
    - pip
  run:
    - python

test:
  requires:
    - pytest
    - sympy
    - numpy

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: python/LICENSE
  summary: Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
