{% set version = "0.14.1" %}
{% set cxx_version = "0.14.0" %}

package:
  name: symengine-wheels
  version: {{ version }}

source:
  - url: https://github.com/symengine/symengine.py/releases/download/v{{ version }}/symengine.py-{{ version }}.tar.gz
    sha256: 3e79d39af5e9f024cd4b8d1372314ac2b83cace7d49cdbad482b4aec5b04c37b
    folder: python
    patches:
      - abi3.diff

  - url: https://github.com/symengine/symengine/releases/download/v{{ cxx_version }}/symengine-{{ cxx_version }}.tar.gz
    sha256: 11c5f64e9eec998152437f288b8429ec001168277d55f3f5f1df78e3cf129707
    folder: cxx

build:
  number: 0
  skip: true    # [py<=38 or (is_abi3 and py>311)]
  python_version_independent: true  # [is_abi3 and py>=311]
  script_env:
    - SYMENGINE_PY_LIMITED_API=3.11   # [is_abi3 and py>=311]
  ignore_run_exports_from:
    - gmp
    - mpfr
    - mpc
    - libflint
    - llvmdev
    - zlib
    - zstd
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}

requirements:
  build:
    - cmake <4
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make   # [unix]
    - ninja  # [win]
    - patchelf        # [linux]
    - python          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - setuptools      # [build_platform != target_platform]
    - unzip           # [unix]
    - m2-unzip        # [win]
    - m2-sed          # [win]
    - cython >=0.29.24
  host:
    - gmp
    - mpfr
    - mpc
    - libflint
    - winpthreads-devel  # [win]
    - llvmdev <17
    # for llvm
    - zlib
    # for llvm
    - zstd
    - python
    - python-abi3                # [is_abi3 and py>=311]
    - setuptools
    - cython >=0.29.24  # [build_platform == target_platform]
    - pip
    - auditwheel      # [linux]
    - delocate        # [win or osx]
  run:
    - python

test:
  requires:
    - pytest
    - sympy
    - numpy   # [not is_freethreading]
    - abi3audit                  # [is_abi3 and py>=311]
  commands:
    - abi3audit ${SP_DIR}/symengine/lib/symengine_wrapper.abi3.so -s -v --assume-minimum-abi3 3.11    # [unix and is_abi3 and py>=311]
    - abi3audit %SP_DIR%/symengine/lib/symengine_wrapper.pyd -s -v --assume-minimum-abi3 3.11         # [win and is_abi3 and py>=311]

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: python/LICENSE
  summary: Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
