{% set version = "0.9.0" %}
{% set cxx_version = "0.9.0" %}

package:
  name: symengine-wheels
  version: {{ version }}

source:
  - url: https://github.com/symengine/symengine.py/releases/download/v{{ version }}/symengine.py-{{ version }}.tar.gz
    sha256: d4d4580f73cd0c00ea0824a7410398a866e0484086f97367409dd868c0fee9ea
    folder: python

  - url: https://github.com/symengine/symengine/releases/download/v{{ cxx_version }}/symengine-{{ cxx_version }}.tar.gz
    sha256: dcf174ac708ed2acea46691f6e78b9eb946d8a2ba62f75e87cf3bf4f0d651724
    folder: cxx

build:
  number: 0
  skip: true  # [(ppc64le or aarch64) and python_impl == "pypy"]
  ignore_run_exports_from:
    - gmp
    - mpfr
    - mpc
    - libflint
    - llvmdev
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [unix]
    - ninja  # [win]
    - unzip           # [unix]
    - patchelf        # [linux]
    - python          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - auditwheel      # [linux]
    - delocate        # [win]
    - pip             # [osx]
    - cython >=0.29.24
  host:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - libflint 2.* *nontl*
    - llvmdev
    - python
    - setuptools
    - cython >=0.29.24
    - pip
  run:
    - python

test:
  requires:
    - pytest
    - sympy
    - numpy

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: python/LICENSE
  summary: Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
